server:
  port: 8092 # 网关端口
spring:
  cloud:
    gateway:
      routes: # 网关路由配置
        - id: elasticjob-demo # 路由id，自定义，只要唯一即可
          #uri: http://127.0.0.1:8090 # 路由的目标地址 http就是固定地址
          uri: lb://elasticjob-demo # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/elasticjob/** # 这个是按照路径匹配，只要以/api/elasticjob/开头就符合要求
        - id: springbatch-demo
          uri: lb://springbatch-demo
          predicates:
            - Path=/api/springbatch/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka