psbc:
  db: 5

fdfs:
  #超时时间
  so-timeout: 1500
  #连接超时时间
  connect-timeout: 600
  reqHost: 20.224.40.88
  reqPort: 8099
  #tracker地址，你的服务器地址+端口
  tracker-list:
    - 20.224.40.88:22122


azkaban:
  azkurl: 20.201.27.71:8081
  zl.azkurl: 20.200.13.152:8083
  azkusername: azkaban
  azkpassword: ENC(t7VVO1nR8aUQb9mHm8Gyxw==)


spring:
  redis:
    cluster:
      max-redirects: 3
      nodes: 20.200.13.157:6379,20.200.13.158:6379,20.200.13.159:6379
    password: ENC(LURc+c/PRZLvbhtaowBLtI3o5xeCEfmmx/K8TedCh9MQWkUC3EmzuB8HUbkrMrmflSftdQS1+ZKS0QD+TuBVChoPhFGBeu2ks/i0hvq6NAM=)
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2


  rabbitmq:
    host: 20.200.13.157,20.200.13.158,20.200.13.159
    port: 5672
    username: admin
    password: TYSD*ra606
    virtual-host: /
    listener:
      concurrency: 10
      max-concurrency: 20
      prefetch: 5
      simple:
        acknowledge-mode: manual #改为手动确认
        #消费者每次从队列获取的消息数量。写多了，如果长时间得不到消费，数据就一直得不到处理
        prefetch: 10
    # 开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true


  shardingsphere:
    datasource:
      taskdb:
        driver-class-name: org.postgresql.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:postgresql://20.200.176.210:5433/taskdb?rewriteBatchedStatements=true
        username: taskdb
        password: ENC(ktTpjJWLQ+cCgls+z/G+DExQbbEirgvN)

      settdb5:
        driver-class-name: org.postgresql.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:postgresql://20.200.176.212:5432/settdb5?rewriteBatchedStatements=true
        username: settdb
        password: ENC(ktTpjJWLQ+cCgls+z/G+DExQbbEirgvN)


      names: taskdb,settdb5
    props:
#      executor:
#        size: '#工作线程数量，默认值: CPU核数'
      sql.show: false
      check.table.metadata.enabled: false
    sharding:
      default-data-source-name: settdb5
      tables:
        active_executing_flows:
            actual-data-nodes: taskdb.active_executing_flows

        active_sla:
            actual-data-nodes: taskdb.active_sla

        execution_flows:
            actual-data-nodes: taskdb.execution_flows

        execution_jobs:
            actual-data-nodes: taskdb.execution_jobs

        execution_logs:
            actual-data-nodes: taskdb.execution_logs

        executor_events:
            actual-data-nodes: taskdb.executor_events

        executors:
            actual-data-nodes: taskdb.executors

        flow_triggers:
            actual-data-nodes: taskdb.flow_triggers

        project_events:
            actual-data-nodes: taskdb.project_events

        project_files:
            actual-data-nodes: taskdb.project_files

        project_flows:
            actual-data-nodes: taskdb.project_flows

        project_permissions:
            actual-data-nodes: taskdb.project_permissions

        project_properties:
            actual-data-nodes: taskdb.project_properties

        project_versions:
            actual-data-nodes: taskdb.project_versions

        projects:
            actual-data-nodes: taskdb.projects

        properties:
            actual-data-nodes: taskdb.properties

        tb_clm_accbat_conf:
            actual-data-nodes: taskdb.tb_clm_accbat_conf

        tb_clm_accbat_record:
            actual-data-nodes: taskdb.tb_clm_accbat_record

        tb_clm_accstlcfg:
            actual-data-nodes: taskdb.tb_clm_accstlcfg

        tb_clm_conf:
            actual-data-nodes: taskdb.tb_clm_conf

        tb_clm_drt_txn_map:
            actual-data-nodes: taskdb.tb_clm_drt_txn_map

        tb_clm_file_trans:
            actual-data-nodes: taskdb.tb_clm_file_trans

        tb_clm_file_trans_ctl:
            actual-data-nodes: taskdb.tb_clm_file_trans_ctl

        tb_clm_http_trans:
            actual-data-nodes: taskdb.tb_clm_http_trans

        tb_clm_jobflow_conf:
            actual-data-nodes: taskdb.tb_clm_jobflow_conf

        tb_clm_mission_inf:
            actual-data-nodes: taskdb.tb_clm_mission_inf

        tb_clm_mission_log:
            actual-data-nodes: taskdb.tb_clm_mission_log

        tb_clm_mq_msg_log:
            actual-data-nodes: taskdb.tb_clm_mq_msg_log

        tb_clm_mq_trans:
            actual-data-nodes: taskdb.tb_clm_mq_trans

        tb_clm_pfb_err:
            actual-data-nodes: taskdb.tb_clm_pfb_err

        tb_clm_acf_err:
            actual-data-nodes: taskdb.tb_clm_acf_err

        tb_clm_trans_file_mission:
            actual-data-nodes: taskdb.tb_clm_trans_file_mission

        tb_clm_txn_conf:
            actual-data-nodes: taskdb.tb_clm_txn_conf

        tb_clm_mer_acc_err:
            actual-data-nodes: taskdb.tb_clm_mer_acc_err

        tb_clm_bat_cut_ctl:
            actual-data-nodes: taskdb.tb_clm_bat_cut_ctl

        tb_clm_msg_cut_ctl:
            actual-data-nodes: taskdb.tb_clm_msg_cut_ctl

        tb_clm_ordtxn_err:
            actual-data-nodes: taskdb.tb_clm_ordtxn_err

        tb_clm_send_msg_stat:
            actual-data-nodes: taskdb.tb_clm_send_msg_stat

        tb_clm_union_fee_sum:
            actual-data-nodes: taskdb.tb_clm_union_fee_sum

        tb_clm_ywch_unmatch:
            actual-data-nodes: taskdb.tb_clm_ywch_unmatch

        tb_clm_yali_unmatch:
            actual-data-nodes: taskdb.tb_clm_yali_unmatch

        tb_clm_balance_detail_check_not_result:
            actual-data-nodes: taskdb.tb_clm_balance_detail_check_not_result

        tb_clm_dynamic_account_notice:
            actual-data-nodes: taskdb.tb_clm_dynamic_account_notice

        tb_clm_yacom_brhsum:
            actual-data-nodes: taskdb.tb_clm_yacom_brhsum

        tb_clm_yali_brhsum:
            actual-data-nodes: taskdb.tb_clm_yali_brhsum

        tb_clm_ywch_brhsum:
            actual-data-nodes: taskdb.tb_clm_ywch_brhsum

        tb_clm_mer_account:
            actual-data-nodes: taskdb.tb_clm_mer_account

        tb_group_mer:
            actual-data-nodes: taskdb.tb_group_mer

        tb_clm_digiccy_unmatch:
            actual-data-nodes: taskdb.tb_clm_digiccy_unmatch

        tb_platform_inst:
            actual-data-nodes: taskdb.tb_platform_inst

        tb_platform_inst_principals:
            actual-data-nodes: taskdb.tb_platform_inst_principals

        tb_clm_ordtxn_rev_err:
            actual-data-nodes: taskdb.tb_clm_ordtxn_rev_err

        tb_clm_file_configuration:
            actual-data-nodes: taskdb.tb_clm_file_configuration

        tb_clm_digiccy_config:
            actual-data-nodes: taskdb.tb_clm_digiccy_config

        tb_clm_freduc_record_digiccy:
            actual-data-nodes: taskdb.tb_clm_freduc_record_digiccy

        tb_clm_freduc_digiccy:
            actual-data-nodes: taskdb.tb_clm_freduc_digiccy

        tb_clm_bat_cut_ctl_err:
            actual-data-nodes: taskdb.tb_clm_bat_cut_ctl_err

        tb_clm_file_trans_err:
            actual-data-nodes: taskdb.tb_clm_file_trans_err

        tb_clm_mission_log_err:
            actual-data-nodes: taskdb.tb_clm_mission_log_err

        tb_clm_mission_seq:
            actual-data-nodes: taskdb.tb_clm_mission_seq

        tb_clm_yali_err_brhsum:
            actual-data-nodes: taskdb.tb_clm_yali_err_brhsum

        tb_outsource_inst:
            actual-data-nodes: taskdb.tb_outsource_inst

        tb_outsource_brh_rate:
            actual-data-nodes: taskdb.tb_outsource_brh_rate

        tb_clm_timectl:
            actual-data-nodes: taskdb.tb_clm_timectl

        tb_clm_summary_digiccy:
            actual-data-nodes: taskdb.tb_clm_summary_digiccy

        tb_clm_digiccy_number:
            actual-data-nodes: taskdb.tb_clm_digiccy_number

        tb_clm_phone_file_notice:
            actual-data-nodes: taskdb.tb_clm_phone_file_notice

        tb_clm_phone_last_notice:
            actual-data-nodes: taskdb.tb_clm_phone_last_notice

        tb_clm_sf_dynamic_account_notice:
            actual-data-nodes: taskdb.tb_clm_sf_dynamic_account_notice

        tb_clm_seq_record:
            actual-data-nodes: taskdb.tb_clm_seq_record

        tb_ris_mcht_dt_sum:
            actual-data-nodes: taskdb.tb_ris_mcht_dt_sum

        tb_ris_mcht_mth_sum:
            actual-data-nodes: taskdb.tb_ris_mcht_mth_sum

        tb_ris_mcht_yer_sum:
            actual-data-nodes: taskdb.tb_ris_mcht_yer_sum

        tb_sett_ris_warn_txn:
            actual-data-nodes: taskdb.tb_sett_ris_warn_txn

        tb_credit_card_tmp:
            actual-data-nodes: taskdb.tb_credit_card_tmp

        tb_credit_merid_tmp:
            actual-data-nodes: taskdb.tb_credit_merid_tmp

        tb_ris_border_brh:
            actual-data-nodes: taskdb.tb_ris_border_brh

        tb_ris_term_dt_sum:
            actual-data-nodes: taskdb.tb_ris_term_dt_sum

        tb_clm_bank_account:
            actual-data-nodes: taskdb.tb_clm_bank_account

        tb_clm_reacc:
            actual-data-nodes: taskdb.tb_clm_reacc

        tb_clm_ris_control_digiccy:
            actual-data-nodes: taskdb.tb_clm_ris_control_digiccy

        tb_clm_config:
            actual-data-nodes: taskdb.tb_clm_config

        tb_clm_new_core_account:
            actual-data-nodes: taskdb.tb_clm_new_core_account

        tb_clm_stopbilling:
            actual-data-nodes: taskdb.tb_clm_stopbilling

        tb_clm_digandfile_config:
            actual-data-nodes: taskdb.tb_clm_digandfile_config

        tb_clm_check_file:
            actual-data-nodes: taskdb.tb_clm_check_file

        tb_bd_bcuser_file_sta:
            actual-data-nodes: taskdb.tb_bd_bcuser_file_sta

        tb_clm_ris_controlnt:
            actual-data-nodes: taskdb.tb_clm_ris_controlnt

        tb_clm_txn_wlsd_conf:
            actual-data-nodes: taskdb.tb_clm_txn_wlsd_conf

        tb_clm_ordtxn_wlsd_rev_err:
            actual-data-nodes: taskdb.tb_clm_ordtxn_wlsd_rev_err

        tb_ris_mcht_dt_sum_nt:
            actual-data-nodes: taskdb.tb_ris_mcht_dt_sum_nt

        tb_ris_mcht_mth_sum_nt:
            actual-data-nodes: taskdb.tb_ris_mcht_mth_sum_nt

        tb_ris_mcht_yer_sum_nt:
            actual-data-nodes: taskdb.tb_ris_mcht_yer_sum_nt

        tb_ris_term_dt_sum_nt:
            actual-data-nodes: taskdb.tb_ris_term_dt_sum_nt

        tb_sett_ris_warn_txn_nt:
            actual-data-nodes: taskdb.tb_sett_ris_warn_txn_nt

        tb_fcp_dtl:
            actual-data-nodes: taskdb.tb_fcp_dtl

        tb_clm_yacomn_brhsum:
            actual-data-nodes: taskdb.tb_clm_yacomn_brhsum

        tb_clm_ywchwlsd_brhsum:
            actual-data-nodes: taskdb.tb_clm_ywchwlsd_brhsum

        tb_clm_yaliwlsd_brhsum:
            actual-data-nodes: taskdb.tb_clm_yaliwlsd_brhsum

        tb_clm_yacomwlsd_brhsum:
            actual-data-nodes: taskdb.tb_clm_yacomwlsd_brhsum

        tb_clm_digiccy_activity_list:
            actual-data-nodes: taskdb.tb_clm_digiccy_activity_list

        tb_clm_digiccy_ranking_day_file:
            actual-data-nodes: taskdb.tb_clm_digiccy_ranking_day_file

        tb_clm_digiccy_scene_redpapre:
            actual-data-nodes: taskdb.tb_clm_digiccy_scene_redpapre

        tb_clm_digiccy_big_data:
            actual-data-nodes: taskdb.tb_clm_digiccy_big_data

        tb_ris_debit_trans_sum:
            actual-data-nodes: taskdb.tb_ris_debit_trans_sum

        tb_clm_sub_ledger:
            actual-data-nodes: taskdb.tb_clm_sub_ledger

        tb_clm_digiccy_wallet_log:
            actual-data-nodes: taskdb.tb_clm_digiccy_wallet_log

        tb_ris_attr_tag:
            actual-data-nodes: taskdb.tb_ris_attr_tag

        tb_ris_tag_sublaw_threshold_set:
            actual-data-nodes: taskdb.tb_ris_tag_sublaw_threshold_set

        tb_ris_mer_rule_result:
            actual-data-nodes: taskdb.tb_ris_mer_rule_result

        tb_ris_norm_info:
            actual-data-nodes: taskdb.tb_ris_norm_info

        tb_brh_tmp:
            actual-data-nodes: taskdb.tb_brh_tmp

        tb_clm_sec_account_chk:
            actual-data-nodes: taskdb.tb_clm_sec_account_chk

        tb_ris_antimodel_info:
            actual-data-nodes: taskdb.tb_ris_antimodel_info

        tb_clm_ris_digiccy:
            actual-data-nodes: taskdb.tb_clm_ris_digiccy

        tb_clm_up_txntype:
            actual-data-nodes: taskdb.tb_clm_up_txntype

        tb_clm_digiccy_calculate:
            actual-data-nodes: taskdb.tb_clm_digiccy_calculate

        tb_clm_digiccy_error_em:
            actual-data-nodes: taskdb.tb_clm_digiccy_error_em

        tb_clm_house_config:
            actual-data-nodes: taskdb.tb_clm_house_config

        tb_clm_wl_ywch_brhsum:
            actual-data-nodes: taskdb.tb_clm_wl_ywch_brhsum

        tb_clm_ptl_fileproc:
            actual-data-nodes: taskdb.tb_clm_ptl_fileproc

        tb_clm_lastmsg_log:
            actual-data-nodes: taskdb.tb_clm_lastmsg_log

        tb_acq_mer_awarn_infoa:
            actual-data-nodes: taskdb.tb_acq_mer_awarn_infoa

        tb_acq_mer_awarn_infob:
            actual-data-nodes: taskdb.tb_acq_mer_awarn_infob

        tb_clm_wl_dztz:
            actual-data-nodes: taskdb.tb_clm_wl_dztz

        tb_clm_digiccy_error_calandcheck:
            actual-data-nodes: taskdb.tb_clm_digiccy_error_calandcheck

        tb_clm_manual_transaction:
            actual-data-nodes: taskdb.tb_clm_manual_transaction

        tb_clm_wl_fkcp_brhsum:
            actual-data-nodes: taskdb.tb_clm_wl_fkcp_brhsum

        tb_clm_wlfk_dztz:
            actual-data-nodes: taskdb.tb_clm_wlfk_dztz

        tb_clm_raffle_send:
            actual-data-nodes: taskdb.tb_clm_raffle_send

        tb_clm_irdmcc_conf:
            actual-data-nodes: taskdb.tb_clm_irdmcc_conf

        tb_clm_irdparam_conf:
            actual-data-nodes: taskdb.tb_clm_irdparam_conf




#SDK settings, please keep value equals with governor settings
pfpj.application.sys-code: DEMO-SYS01
pfpj.application.sys-key: DEMO-SYS01-KEY
pfpj.accesscontrol.enabled: false

#Eureka settings
eureka.client.enabled: true
eureka.instance.prefer-ip-address: true
eureka.instance.lease-renewal-interval-in-seconds: 10
eureka.instance.lease-expiration-duration-in-seconds: 30
eureka.client.service-url.defaultZone: http://nap:TYSD_2020@20.200.13.157:8761/eureka/,http://nap:TYSD_2020@20.200.13.158:8761/eureka/,http://nap:TYSD_2020@20.200.13.159:8761/eureka/
eureka.servername.datasync: PSBC-DATASYNC-PROVIDER
eureka.servername.bigdatastlacctbal: NAP-ACT-SRV
eureka.servername.accajust: NAP-FULLQR-SRV

apollo.bootstrap.enabled: false
apollo.meta: http://apollo-config-server-ip:port/


feign.client.config.default.connect-timeoout: 30000
feign.client.config.default.read-timeoout: 30000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


