spring:
  application:
    name: demo
  profiles:
    active: sit05
  batch:
    job:
      enabled: false #默认启动后不自动执行job
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.psbc.psbccommon.mode